Repository gisat-panther/ptr-state, pull requests merged in 2020-07, with the labels that each got.

#26 Add auto to make automatic releases
  .autorc
  .github/workflows/release.yml
  .github/workflows/tag-validation.yml
  package-lock.json
  package.json
Labels: patch

#32 Add auto to make automatic releases
  .autorc
  .github/workflows/release.yml
  .github/workflows/tag-validation.yml
  package-lock.json
  package.json
Labels: patch

#33 Workflows: more names
  .github/workflows/tag-validation.yml
  .github/workflows/test.yml
Labels: skip-release

#34 Fix/caching
  src/state/Maps/actions.js
  src/state/Maps/selectors.js
Labels: patch

#35 Fix release
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: patch

#36 maps - set map set layers
  src/constants/ActionTypes.js
  src/state/Maps/actions.js
  src/state/Maps/reducers.js
Labels: patch

#38 Maps reducers - add layer - do not use setMap helper
  src/state/Maps/reducers.js
Labels: patch

#40 Selections - enable to add data from view
  src/state/Selections/actions.js
Labels: patch

#25 Fix/nav list and maps
  package-lock.json
  package.json
  src/components/NavList/index.js
  src/components/NavList/navlist.scss
  src/components/NavList/presentation.js
  src/components/connects.js
  src/state/Maps/helpers.js
Labels: minor

#27 Add common actions tests
  src/state/_common/actions.js
  src/state/_common/request.js
  tests/state/_common/actions-test.js
Labels: patch

#41 Get WMS layer option from layer confuguration
  src/state/Maps/helpers.js
Labels: patch
